using Application.Features.CentralDbSync.Config;
using Application.Features.CentralDbSync.Mapping;
using static Application.Features.CentralDbSync.Config.Rules.MappingRuleCatalogFactory;

namespace Application.Features.CentralDbSync.Config.Rules.IPO.Fabric;

public sealed class IpoFabricMasterGroupDetailMappingRuleCatalog : ITableMappingRuleCatalog
{
    public IReadOnlyList<TableMappingRule> GetRules() =>
    [
        Create(
            ruleName: "ERP.IPO.Fabrics.Masters.Groups.Details",
            sourceTable: "ERP.IPO.Fabrics.Masters.Groups.Details",
            sourcePrimaryKey: "IPOFabricMasterGroupDetailId",
            targetTable: "ipo_fabrics_masters_groups_details",
            targetPrimaryKey: "ipo_fabric_master_group_detail_id",
            syncTier: "Hot",
            filterCompany: true,
            columns:
            [
                MapPk("ipo_fabric_master_group_detail_id", "integer", "t0.IPOFabricMasterGroupDetailId"),
                Map("ipo_fabric_master_group_id", "integer", "t0.IPOFabricMasterGroupId"),
                Map("ipo_fabric_item_id", "integer", "t0.IPOFabricItemId"),
                Map("company_id", "integer", "t0.CompanyId"),
                Map("po_styles_id", "integer", "t0.StyleId"),
                Map("po_id", "integer", "t0.PurchaseOrderId"),
                Map("work_type", "integer", "t0.WorkType"),
                Map("seasons_id", "integer", "t0.SeasonId"),
                Map("customer_id", "integer", "t0.CustomerPartnerId"),
                Map("supplier_id", "integer", "t0.SupplierPartnerId"),
                Map("ipo_fabric_item_code", "text", "t0.IPOFabricItemCode"),
                Map("po_style_fabrics_id", "integer", "t0.StyleFabricId"),
                Map("fabric_master_id", "integer", "t0.FabricSupplierId"),
                Map("fabric_supplier_code", "text", "t0.FabricSupplierCode"),
                Map("fabric_supplier_name", "text", "t0.FabricSupplierName"),
                Map("color_ext", "text", "t0.ColorExt"),
                Map("fabric_types_id", "integer", "t0.FabricTypeId"),
                Map("group_fabric_type_id", "integer", "t0.GroupFabricTypeId"),
                Map("fabric_color_option", "integer", "t0.FabricColorOption"),
                Map("pantone", "text", "t0.Pantone"),
                Map("cut_width", "numeric", "t0.CutWidth"),
                Map("units_id", "integer", "t0.UnitId"),
                Map("fabric_colors_id", "integer", "t0.FabricColorId"),
                Map("style_fabric_lab_dip_id", "integer", "t0.StyleFabricLabDipId"),
                Map("ref_style_fabric_lab_dip_id", "integer", "t0.Ref_StyleFabricLabDipId"),
                Map("shadeband_id", "integer", "t0.ShadebandId"),
                Map("ld_code", "text", "t0.LDCode"),
                Map("ld_shadeband", "text", "t0.LDShadeband"),
                Map("treatment_types", "text", "t0.TreatmentTypes"),
                Map("fabric_costing_sheet_id", "integer", "t0.FabricCostingSheetId"),
                Map("costing_sheet_id", "integer", "t0.CostingSheetId"),
                Map("cs_ship_mode", "integer", "t0.CSShipMode"),
                Map("cs_price", "numeric", "t0.CSPrice"),
                Map("actual_ship_mode", "integer", "t0.ActualShipMode"),
                Map("unit_price", "numeric", "t0.UnitPrice"),
                Map("style_total_final_qty", "numeric", "t0.StyleTotalFinalQty"),
                Map("style_technical_rating_id", "integer", "t0.StyleTechnicalRatingId"),
                Map("consumption_matrix_id", "integer", "t0.FabricRatingDetailId"),
                Map("rating_value", "numeric", "t0.RatingValue"),
                Map("qty", "numeric", "t0.Qty"),
                Map("test", "numeric", "t0.Test"),
                Map("total_qty", "numeric", "t0.TotalQty"),
                Map("pre_arrival", "numeric", "t0.PreArrival"),
                Map("blanket_test", "boolean", "t0.BlanketTest"),
                Map("ipo_reason_id", "integer", "t0.IPOReasonId"),
                Map("ipo_fabric_status", "integer", "t0.IPOFabricStatus"),
                Map("sent_pur_date", "timestamp", "t0.SentPurDate"),
                Map("sent_pur_by_user_id", "integer", "t0.SentPurByUserId"),
                Map("ipo_fabric_master_code", "text", "t0.IPOFabricMasterCode"),
                Map("shipping_sample", "boolean", "t0.ShippingSample"),
                Map("created_date", "timestamp", "t0.CreatedDate"),
                Map("treatment_type_ids", "text", "t0.TreatmentTypeIds"),
                Map("expect_stock_in_date", "timestamp", "t0.ExpectStockInDate"),
                Map("confirm_expect_stock_in_date", "timestamp", "t0.ConfirmExpectStockInDate"),
                Map("deposit", "boolean", "t0.Deposit"),
                Map("ipo_cancellation_id", "integer", "t0.IPOCancellationId"),
                Map("created_by_user_id", "integer", "t0.CreatedByUserId"),
                Map("updated_date", "timestamp", "t0.UpdatedDate"),
                Map("updated_by_user_id", "integer", "t0.UpdatedByUserId"),
                Map("revised_stock_in_date", "timestamp", "t0.RevisedStockInDate"),
                Map("ld_code_option_actual", "text", "t0.LDCode_OptionActual"),
                Map("drops_id", "integer", "t0.DropId"),
                Map("process_type_id", "integer", "t0.ProcessTypeId"),
                Map("item_code", "text", "t0.ItemCode"),
                Map("purchase_order_created_date", "timestamp", "t0.PurchaseOrderCreatedDate"),
                Map("remark_of_mer", "text", "t0.RemarkOfMer"),
                Map("shipment_date_max", "timestamp", "t0.ShipmentDateMax"),
                Map("start_received_date", "timestamp", "t0.StartReceivedDate"),
                Map("stock_in_date", "timestamp", "t0.StockInDate"),
                Map("cd_status", "integer", "t0.CDStatus"),
                Map("last_reason_revised_stock_in_date_id", "integer", "t0.LastReasonRevisedStockInDateId"),
                Map("shipment_internal_date_max", "timestamp", "t0.ShipmentInternalDateMax"),
                Map("fabric_color_input_manual", "text", "t0.FabricColorInputManual")
            ])
    ];
}
