using Application.Features.CentralDbSync.Config;
using Application.Features.CentralDbSync.Mapping;
using static Application.Features.CentralDbSync.Config.Rules.MappingRuleCatalogFactory;

namespace Application.Features.CentralDbSync.Config.Rules.IPO.Fabric;

public sealed class IpoFabricMasterGroupInspectionRequestLotMappingRuleCatalog : ITableMappingRuleCatalog
{
    public IReadOnlyList<TableMappingRule> GetRules() =>
    [
        Create(
            ruleName: "ERP.IPO.Fabrics.Masters.Groups.InspectionRequests.LOTs",
            sourceTable: "ERP.IPO.Fabrics.Masters.Groups.InspectionRequests.LOTs",
            sourcePrimaryKey: "IPOFabricMasterGroupInspectionRequestLOTId",
            targetTable: "ipo_fabrics_masters_groups_insp_request_lots",
            targetPrimaryKey: "ipo_fabric_master_group_insp_request_lot_id",
            syncTier: "Hot",
            filterCompany: true,
            columns:
            [
                MapPk("ipo_fabric_master_group_insp_request_lot_id", "integer", "t0.IPOFabricMasterGroupInspectionRequestLOTId"),
                Map("company_id", "integer", "t0.CompanyId"),
                Map("ipo_fabric_master_group_inspection_request_id", "integer", "t0.IPOFabricMasterGroupInspectionRequestId"),
                Map("ipo_fabric_master_group_receiving_id", "integer", "t0.LotReceivingId"),
                Map("ipo_fabric_master_group_insp_request_lot_id_parent", "integer", "t0.IPOFabricMasterGroupInspectionRequestLOTIdParent"),
                Map("po_id", "integer", "t0.PurchaseOrderId"),
                Map("shipping_sample_request_id", "integer", "t0.ShippingSampleRequestId"),
                Map("final_result", "boolean", "t0.FinalResult"),
                Map("weight", "boolean", "t0.Weight"),
                Map("weight_result", "boolean", "t0.Weight_Result"),
                Map("shrinkage", "boolean", "t0.Shrinkage"),
                Map("shrinkage_result", "boolean", "t0.Shrinkage_Result"),
                Map("skewing", "boolean", "t0.Skewing"),
                Map("skewing_result", "boolean", "t0.Skewing_Result"),
                Map("crocking", "boolean", "t0.Crocking"),
                Map("crocking_result", "boolean", "t0.Crocking_Result"),
                Map("colorfastness", "boolean", "t0.Colorfastness"),
                Map("colorfastness_result", "boolean", "t0.Colorfastness_Result"),
                Map("printingtest", "boolean", "t0.Printingtest"),
                Map("printingtest_result", "boolean", "t0.Printingtest_Result"),
                Map("twisting", "boolean", "t0.Twisting"),
                Map("twisting_result", "boolean", "t0.Twisting_Result"),
                Map("sent_to_qa_lab", "boolean", "t0.SentToQALab"),
                Map("sent_to_qa_lab_date", "timestamp", "t0.SentToQALabDate"),
                Map("sent_to_qa_lab_user_id", "integer", "t0.SentToQALabUserId"),
                Map("qa_received_cut_test_date", "timestamp", "t0.QAReceivedCutTestDate"),
                Map("physical_sent_to_qa_lab", "boolean", "t0.Physical_SentToQALab"),
                Map("physical_sent_to_qa_lab_date", "timestamp", "t0.Physical_SentToQALabDate"),
                Map("qa_received_date", "timestamp", "t0.QAReceivedDate"),
                Map("qa_received_user_id", "integer", "t0.QAReceivedUserId"),
                Map("qa_finished_date", "timestamp", "t0.QAFinishedDate"),
                Map("test_treatment_meter_qty", "numeric", "t0.TestTreatmentMeterQty"),
                Map("test_flat_rib_pieces_qty", "numeric", "t0.TestFlatRibPiecesQty"),
                Map("total_actual_cut_defects", "integer", "t0.TotalActualCutDefects"),
                Map("total_final_cut_qty", "numeric", "t0.TotalFinalCutQty"),
                Map("total_gross_plus_qty", "numeric", "t0.TotalGrossPlusQty"),
                Map("total_gross_return_qty", "numeric", "t0.TotalGrossReturnQty"),
                Map("total_net_return_qty", "numeric", "t0.TotalNetReturnQty"),
                Map("total_actual_length", "numeric", "t0.TotalActualLength"),
                Map("total_actual_gross_qty", "numeric", "t0.TotalActualGrossQty"),
                Map("total_actual_net_qty", "numeric", "t0.TotalActualNetQty"),
                Map("remark", "text", "t0.Remark"),
                Map("remark_of_qa", "text", "t0.RemarkOfQA"),
                Map("remark_of_color_shade", "text", "t0.RemarkOfColorShade"),
                Map("remark_of_lot", "text", "t0.RemarkOfLot"),
                Map("fabric_inspection_type", "integer", "t0.FabricInspectionType"),
                Map("total_roll_per_request", "integer", "t0.TotalRollPerRequest"),
                Map("ld_type", "integer", "t0.LDType"),
                Map("state", "integer", "t0.State"),
                Map("purchase_order_created_date", "timestamp", "t0.PurchaseOrderCreatedDate"),
                Map("physical_inps", "boolean", "t0.PhysicalInps"),
                Map("manual_physical_insp", "boolean", "t0.ManualPhysicalInsp"),
                Map("manual_physical_insp_by_user_id", "integer", "t0.ManualPhysicalInspByUserId"),
                Map("manual_physical_insp_date", "timestamp", "t0.ManualPhysicalInspDate"),
                Map("manual_physical_insp_remark", "text", "t0.ManualPhysicalInspRemark"),
                Map("manual_special_insp", "integer", "t0.ManualSpecialInsp"),
                Map("manual_special_insp_remark", "text", "t0.ManualSpecialInspRemark"),
                Map("manual_special_insp_by_user_id", "integer", "t0.ManualSpecialInspByUserId"),
                Map("manual_special_insp_date", "timestamp", "t0.ManualSpecialInspDate"),
                Map("manual_special_insp_attach_file", "text", "t0.ManualSpecialInspAttachFile"),
                Map("manual_appearance_insp", "boolean", "t0.ManualAppearanceInsp"),
                Map("manual_appearance_insp_by_user_id", "integer", "t0.ManualAppearanceInspByUserId"),
                Map("manual_appearance_insp_date", "timestamp", "t0.ManualAppearanceInspDate"),
                Map("total_percent_major", "numeric", "t0.TotalPercentMajor"),
                Map("total_percent_major_reload", "numeric", "t0.TotalPercentMajorReload"),
                Map("appearance_inps", "boolean", "t0.AppearanceInps"),
                Map("appearance_inps_commercial", "boolean", "t0.AppearanceInpsCommercial"),
                Map("color_shade_lot_result", "integer", "t0.ColorShadeLotResult"),
                Map("stock_in_date", "timestamp", "t0.StockInDate"),
                Map("stock_in_user_id", "integer", "t0.StockInUserId"),
                Map("final_finish_date", "timestamp", "t0.FinalFinishDate"),
                Map("canceled_reason", "text", "t0.CanceledReason"),
                Map("percent_appearance", "numeric", "t0.PercentAppearance"),
                Map("total_roll_must_test_appearance", "integer", "t0.TotalRollMustTestAppearance"),
                Map("location_ids", "text", "t0.LocationIds"),
                Map("location_names", "text", "t0.LocationNames"),
                Map("commercial_pass", "boolean", "t0.CommercialPass"),
                Map("lot_final_result_root", "boolean", "t0.LotFinalResultRoot"),
                Map("lot_final_result", "boolean", "t0.LotFinalResult"),
                Map("return_to_supplier", "boolean", "t0.ReturnToSupplier"),
                Map("return_roll_to_supplier", "boolean", "t0.ReturnRollToSupplier"),
                Map("has_request_return_to_supplier", "boolean", "t0.HasRequestReturnToSupplier"),
                Map("qa_reviewed", "boolean", "t0.QAReviewed"),
                Map("qa_reviewed_by_user_id", "integer", "t0.QAReviewedByUserId"),
                Map("qa_reviewed_date", "timestamp", "t0.QAReviewedDate"),
                Map("last_physical_action_by_id", "integer", "t0.LastPhysicalActionById"),
                Map("last_physical_action_date", "timestamp", "t0.LastPhysicalActionDate"),
                Map("pur_reviewed_date", "timestamp", "t0.PurReviewedDate"),
                Map("pur_reviewed_user_id", "integer", "t0.PurReviewedUserId"),
                Map("report_last_modified_date", "timestamp", "t0.ReportLastModifiedDate"),
                Map("review_phycical_test", "boolean", "t0.ReviewPhycicalTest"),
                Map("total_qty_arrived", "numeric", "t0.TotalQtyArrived"),
                Map("actual_qty_gross", "numeric", "t0.ActualQtyGross"),
                Map("actual_qty_net", "numeric", "t0.ActualQtyNet"),
                Map("total_gross", "numeric", "t0.TotalGross"),
                Map("total_net", "numeric", "t0.TotalNet"),
                Map("total_weight", "numeric", "t0.TotalWeight"),
                Map("total_error_major", "integer", "t0.TotalErrorMajor"),
                Map("total_quantity_major", "numeric", "t0.TotalQuantityMajor"),
                Map("avg_defect_major", "numeric", "t0.AvgDefectMajor"),
                Map("total_avg_defect_major", "numeric", "t0.TotalAvgDefectMajor"),
                Map("total_roll_pass", "integer", "t0.TotalRollPass"),
                Map("min_end_meter", "numeric", "t0.MinEndMeter"),
                Map("actual_qty_checked", "numeric", "t0.ActualQtyChecked"),
                Map("total_after_returned_weight", "numeric", "t0.TotalAfterReturnedWeight"),
                Map("total_after_returned_gross", "numeric", "t0.TotalAfterReturnedGross"),
                Map("total_after_returned_net", "numeric", "t0.TotalAfterReturnedNet"),
                Map("total_after_returned_error_major", "numeric", "t0.TotalAfterReturnedErrorMajor"),
                Map("total_after_returned_quantity_major", "numeric", "t0.TotalAfterReturnedQuantityMajor"),
                Map("total_after_returned_percent_major", "numeric", "t0.TotalAfterReturnedPercentMajor"),
                Map("after_returned_avg_defect_major", "numeric", "t0.AfterReturnedAvgDefectMajor"),
                Map("total_after_returned_avg_defect_major", "numeric", "t0.TotalAfterReturnedAvgDefectMajor"),
                Map("total_after_returned_roll_pass", "integer", "t0.TotalAfterReturnedRollPass"),
                Map("after_returned_min_end_meter", "integer", "t0.AfterReturnedMinEndMeter"),
                Map("after_returned_actual_qty_checked", "numeric", "t0.AfterReturnedActualQtyChecked"),
                Map("total_returned_net", "numeric", "t0.TotalReturnedNet"),
                Map("total_after_commercial_pass_weight", "numeric", "t0.TotalAfterCommercialPassWeight"),
                Map("total_after_commercial_pass_gross", "numeric", "t0.TotalAfterCommercialPassGross"),
                Map("total_after_commercial_pass_net", "numeric", "t0.TotalAfterCommercialPassNet"),
                Map("total_after_commercial_pass_error_major", "numeric", "t0.TotalAfterCommercialPassErrorMajor"),
                Map("total_after_commercial_pass_quantity_major", "numeric", "t0.TotalAfterCommercialPassQuantityMajor"),
                Map("total_after_commercial_pass_percent_major", "numeric", "t0.TotalAfterCommercialPassPercentMajor"),
                Map("after_commercial_pass_avg_defect_major", "numeric", "t0.AfterCommercialPassAvgDefectMajor"),
                Map("total_after_commercial_pass_avg_defect_major", "numeric", "t0.TotalAfterCommercialPassAvgDefectMajor"),
                Map("total_after_commercial_pass_roll_pass", "integer", "t0.TotalAfterCommercialPassRollPass"),
                Map("after_commercial_pass_min_end_meter", "integer", "t0.AfterCommercialPassMinEndMeter"),
                Map("after_commercial_pass_actual_qty_checked", "numeric", "t0.AfterCommercialPassActualQtyChecked"),
                Map("logs", "text", "t0.Logs"),
                Map("created_by_user_id", "integer", "t0.CreatedByUserId"),
                Map("created_date", "timestamp", "t0.CreatedDate"),
                Map("updated_by_user_id", "integer", "t0.UpdatedByUserId"),
                Map("updated_date", "timestamp", "t0.UpdatedDate"),
                Map("canceled_by_user_id", "integer", "t0.CanceledByUserId"),
                Map("canceled_date", "timestamp", "t0.CanceledDate"),
                Map("last_report_qa_remark", "text", "t0.LastReportQARemark")
            ])
    ];
}
