using Application.Features.CentralDbSync.Config;
using Application.Features.CentralDbSync.Mapping;
using static Application.Features.CentralDbSync.Config.Rules.MappingRuleCatalogFactory;

namespace Application.Features.CentralDbSync.Config.Rules.IPO.Fabric;

public sealed class IpoFabricMasterGroupMappingRuleCatalog : ITableMappingRuleCatalog
{
    public IReadOnlyList<TableMappingRule> GetRules() =>
    [
        Create(
            ruleName: "ERP.IPO.Fabrics.Masters.Groups",
            sourceTable: "ERP.IPO.Fabrics.Masters.Groups",
            sourcePrimaryKey: "IPOFabricMasterGroupId",
            targetTable: "ipo_fabrics_masters_groups",
            targetPrimaryKey: "ipo_fabric_master_group_id",
            syncTier: "Hot",
            filterCompany: true,
            columns:
            [
                MapPk("ipo_fabric_master_group_id", "integer", "t0.IPOFabricMasterGroupId"),
                Map("ipo_fabric_master_group_code", "text", "t0.IPOFabricMasterGroupCode"),
                Map("ipo_fabric_master_id", "integer", "t0.IPOFabricMasterId"),
                Map("company_id", "integer", "t0.CompanyId"),
                Map("ipo_fabric_item_code_combined", "text", "t0.IPOFabricItemCodeCombined"),
                Map("ld_code", "text", "t0.LDCode"),
                Map("ld_shadeband", "text", "t0.LDShadeband"),
                Map("ld_code_option", "text", "t0.LDCodeOption"),
                Map("partner_id", "integer", "t0.PartnerId"),
                Map("supplier_id", "integer", "t0.SupplierPartnerId"),
                Map("customer_id", "integer", "t0.CustomerPartnerId"),
                Map("fabric_master_id", "integer", "t0.FabricSupplierId"),
                Map("fabric_colors_id", "integer", "t0.FabricColorId"),
                Map("fabric_supplier_code", "text", "t0.FabricSupplierCode"),
                Map("fabric_supplier_name", "text", "t0.FabricSupplierName"),
                Map("cut_width", "numeric", "t0.CutWidth"),
                Map("item_code", "text", "t0.ItemCode"),
                Map("purchase_order_created_date", "timestamp", "t0.PurchaseOrderCreatedDate"),
                Map("treatment_type_ids", "text", "t0.TreatmentTypeIds"),
                Map("treatment_types", "text", "t0.TreatmentTypes"),
                Map("group_fabric_type_ids", "text", "t0.GroupFabricTypeIds"),
                Map("group_fabric_types", "text", "t0.GroupFabricTypes"),
                Map("actual_ship_mode_name", "text", "t0.ActualShipModeName"),
                Map("units_id", "integer", "t0.UnitId"),
                Map("avg_unit_price", "numeric", "t0.AVGUnitPrice"),
                Map("total_order_qty", "numeric", "t0.TotalOrderQty"),
                Map("raw_total_order_qty", "numeric", "t0.RawTotalOrderQty"),
                Map("inventory", "numeric", "t0.Inventory"),
                Map("actual_order_qty", "numeric", "t0.ActualOrderQty"),
                Map("actual_unit_price", "numeric", "t0.ActualUnitPrice"),
                Map("under_moq", "boolean", "t0.UnderMOQ"),
                Map("under_mcq", "boolean", "t0.UnderMCQ"),
                Map("surcharge", "numeric", "t0.Surcharge"),
                Map("actual_amount", "numeric", "t0.ActualAmount"),
                Map("raw_actual_amount", "numeric", "t0.RawActualAmount"),
                Map("tolerance_plus", "numeric", "t0.TolerancePlus"),
                Map("tolerance_minus", "numeric", "t0.ToleranceMinus"),
                Map("raw_pre_arrival", "numeric", "t0.RawPreArrival"),
                Map("pre_arrival", "numeric", "t0.PreArrival"),
                Map("po_type", "integer", "t0.POType"),
                Map("location_names", "text", "t0.LocationNames"),
                Map("location_ids", "text", "t0.LocationIds"),
                Map("fabric_receiving_remark", "text", "t0.FabricReceivingRemark"),
                Map("pur_remark", "text", "t0.PurRemark"),
                Map("mer_remark", "text", "t0.MerRemark"),
                Map("commercial_remark", "text", "t0.CommercialRemark"),
                Map("canceled_reasons", "text", "t0.CanceledReasons"),
                Map("shipping_sample", "boolean", "t0.ShippingSample"),
                Map("total_lot_send_receiving", "integer", "t0.TotalLotSendReceiving"),
                Map("total_lot_add_by_wh", "integer", "t0.TotalLotAddByWH"),
                Map("total_all_lot_of_wh", "integer", "t0.TotalAllLotOfWH"),
                Map("total_lot", "integer", "t0.TotalLOT"),
                Map("total_qty_by_lot", "numeric", "t0.TotalQtyByLOT"),
                Map("status", "integer", "t0.Status"),
                Map("result_date", "timestamp", "t0.ResultDate"),
                Map("total_passed", "integer", "t0.TotalPassed"),
                Map("total_fail", "integer", "t0.TotalFail"),
                Map("ld_type", "integer", "t0.LDType"),
                Map("eta_fabric_received_date", "timestamp", "t0.ETAFabricReceivedDate"),
                Map("max_eta_fabric_stock_in_date", "timestamp", "t0.MaxEtaFabricStockinDate"),
                Map("revised_eta_fabric_received_date", "timestamp", "t0.RevisedETAFabricReceivedDate"),
                Map("revised_max_eta_fabric_stock_in_date", "timestamp", "t0.RevisedMaxEtaFabricStockinDate"),
                Map("eta_shipping_sample_received_date", "timestamp", "t0.ETAShippingSampleReceivedDate"),
                Map("act_shipping_sample_received_date", "timestamp", "t0.ActShippingSampleReceivedDate"),
                Map("total_roll", "integer", "t0.TotalRoll"),
                Map("lot_receive", "integer", "t0.LOTReceive"),
                Map("qty_receive", "numeric", "t0.QtyReceive"),
                Map("balance", "numeric", "t0.Balance"),
                Map("send_qa", "boolean", "t0.SendQA"),
                Map("last_qa_date", "timestamp", "t0.LastQADate"),
                Map("wh_can_receiving", "boolean", "t0.WHCanReceiving"),
                Map("all_lot_sent_to_receiving", "boolean", "t0.AllLOTSentToReceiving"),
                Map("returned_qty", "numeric", "t0.ReturnedQty"),
                Map("remain_qty_receive_after_returned", "numeric", "t0.RemainQtyReceiveAfterReturned"),
                Map("last_qa_user_id", "integer", "t0.LastQAUserId"),
                Map("shipment_date_max", "timestamp", "t0.ShipmentDateMax"),
                Map("shipment_date_min", "timestamp", "t0.ShipmentDateMin"),
                Map("shipment_internal_date_max", "timestamp", "t0.ShipmentInternalDateMax"),
                Map("style_ids", "text", "t0.StyleIds"),
                Map("style_names", "text", "t0.StyleNames"),
                Map("style_no_internals", "text", "t0.StyleNoInternals"),
                Map("sku_no_internals", "text", "t0.SkuNoInternals"),
                Map("style_color_name_codes", "text", "t0.StyleColorNameCodes"),
                Map("combined_pantones", "text", "t0.CombinedPantones"),
                Map("min_expect_stock_in_date", "timestamp", "t0.MinExpectStockInDate"),
                Map("confirm_expect_stock_in_date", "timestamp", "t0.ConfirmExpectStockInDate"),
                Map("purch_actual_ship_mode", "integer", "t0.PurchActualShipMode"),
                Map("last_reason_revised_stock_in_date_id", "integer", "t0.LastReasonRevisedStockInDateId"),
                Map("revised_stock_in_date", "timestamp", "t0.RevisedStockInDate"),
                Map("start_received_date", "timestamp", "t0.StartReceivedDate"),
                Map("last_received_date_of_receiving", "timestamp", "t0.LastReceivedDateOfReceiving"),
                Map("last_received_date", "timestamp", "t0.LastReceivedDate"),
                Map("last_received_user_id", "integer", "t0.LastReceivedUserId"),
                Map("percent_received_qty", "numeric", "t0.PercentReceivedQty"),
                Map("start_qc_fabric_checked_date", "timestamp", "t0.StartQCFabricCheckedDate"),
                Map("percent_qc_fabric_checked_qty", "numeric", "t0.PercentQCFabricCheckedQty"),
                Map("start_qa_lab_checked_date", "timestamp", "t0.StartQALabCheckedDate"),
                Map("percent_qa_lab_checked", "numeric", "t0.PercentQALabChecked"),
                Map("start_qa_fabric_checked_date", "timestamp", "t0.StartQAFabricCheckedDate"),
                Map("percent_qa_fabric_checked", "numeric", "t0.PercentQAFabricChecked"),
                Map("first_stock_in_date", "timestamp", "t0.FirstStockinDate"),
                Map("stock_in_date", "timestamp", "t0.StockInDate"),
                Map("percent_stock_in_qty", "numeric", "t0.PercentStockInQty"),
                Map("sum_net", "numeric", "t0.SumNet"),
                Map("season_names", "text", "t0.SeasonNames"),
                Map("season_ids", "text", "t0.SeasonIds"),
                Map("purchase_order_ids", "text", "t0.PurchaseOrderIds"),
                Map("order_internal_codes", "text", "t0.OrderInternalCodes"),
                Map("order_external_codes", "text", "t0.OrderExternalCodes"),
                Map("drop_codes", "text", "t0.DropCodes"),
                Map("drop_ids", "text", "t0.DropIds"),
                Map("process_type_names", "text", "t0.ProcessTypeNames"),
                Map("process_type_ids", "text", "t0.ProcessTypeIds"),
                Map("total_lot_send_qa_lab", "integer", "t0.TotalLOTSendQALab"),
                Map("total_lot_send_qa_fabric_checked", "numeric", "t0.TotalLOTSendQAFabricChecked"),
                Map("total_actual_qty_checked_send_qa", "numeric", "t0.TotalActualQtyCheckedSendQA"),
                Map("cut_test_date", "timestamp", "t0.CutTestDate"),
                Map("color_exts", "text", "t0.ColorExts"),
                Map("total_lot_checked_by_physical", "integer", "t0.TotalLotCheckedByPhysical"),
                Map("ld_code_option_actual", "text", "t0.LDCode_OptionActual"),
                Map("send_shipping_sample_to_pur_date", "timestamp", "t0.SendShippingSampleToPurDate"),
                Map("pur_received_shipping_sample_date", "timestamp", "t0.PurReceivedShippingSampleDate"),
                Map("po_status", "integer", "t0.POStatus"),
                Map("is_paid", "boolean", "t0.IsPaid"),
                Map("payment_updated_date", "timestamp", "t0.PaymentUpdatedDate"),
                Map("payment_updated_user_id", "integer", "t0.PaymentUpdatedUserId")
            ])
    ];
}
