using Application.Features.CentralDbSync.Config;
using Application.Features.CentralDbSync.Mapping;
using static Application.Features.CentralDbSync.Config.Rules.MappingRuleCatalogFactory;

namespace Application.Features.CentralDbSync.Config.Rules.IPO.Trim;

public sealed class IpoTrimMasterGroupDetailMappingRuleCatalog : ITableMappingRuleCatalog
{
    public IReadOnlyList<TableMappingRule> GetRules() =>
    [
        Create(
            ruleName: "ERP.IPO.Trims.Masters.Groups.Details",
            sourceTable: "ERP.IPO.Trims.Masters.Groups.Details",
            sourcePrimaryKey: "IPOTrimMasterGroupDetailId",
            targetTable: "ipo_trims_masters_groups_details",
            targetPrimaryKey: "ipo_trim_master_group_detail_id",
            syncTier: "Hot",
            filterCompany: true,
            columns:
            [
                MapPk("ipo_trim_master_group_detail_id", "integer", "t0.IPOTrimMasterGroupDetailId"),
                Map("ipo_trim_master_group_id", "integer", "t0.IPOTrimMasterGroupId"),
                Map("ipo_trim_master_id", "integer", "t0.IPOTrimMasterId"),
                Map("ipo_trim_item_id", "integer", "t0.IPOTrimItemId"),
                Map("ipo_trim_item_code", "text", "t0.IPOTrimItemCode"),
                Map("company_id", "integer", "t0.CompanyId"),
                Map("po_styles_id", "integer", "t0.StyleId"),
                Map("po_id", "integer", "t0.PurchaseOrderId"),
                Map("style_categories_id", "integer", "t0.StyleCategoryId"),
                Map("style_colour_id", "integer", "t0.StyleColorId"),
                Map("pantone", "text", "t0.Pantone"),
                Map("nominated", "integer", "t0.Nominated"),
                Map("work_type", "integer", "t0.WorkType"),
                Map("seasons_id", "integer", "t0.SeasonId"),
                Map("customer_id", "integer", "t0.CustomerPartnerId"),
                Map("supplier_id", "integer", "t0.SupplierPartnerId"),
                Map("po_styles_trims_id", "integer", "t0.StyleTrimId"),
                Map("trims_master_id", "integer", "t0.TrimSupplierId"),
                Map("trim_supplier_code", "text", "t0.TrimSupplierCode"),
                Map("trim_supplier_name", "text", "t0.TrimSupplierName"),
                Map("ipo_reason_id", "integer", "t0.IPOReasonId"),
                Map("ipo_trim_status", "integer", "t0.IPOTrimStatus"),
                Map("sent_pur_date", "timestamp", "t0.SentPurDate"),
                Map("sent_pur_by_user_id", "integer", "t0.SentPurByUserId"),
                Map("created_date", "timestamp", "t0.CreatedDate"),
                Map("remark_of_pur", "text", "t0.RemarkOfPur"),
                Map("remark_of_mer", "text", "t0.RemarkOfMer"),
                Map("trim_kinds_id", "integer", "t0.KindOfTrimId"),
                Map("trim_types_id", "integer", "t0.TypeOfTrimId"),
                Map("trims_compositions_id", "integer", "t0.TrimCompositionId"),
                Map("colours_id", "integer", "t0.ColorId"),
                Map("units_id", "integer", "t0.UnitId"),
                Map("dimension_of_technical", "text", "t0.DimensionOfTechnical"),
                Map("dimension_of_trim", "text", "t0.DimensionOfTrim"),
                Map("size_id", "integer", "t0.SizeId"),
                Map("rating_value", "numeric", "t0.RatingValue"),
                Map("qty", "numeric", "t0.Qty"),
                Map("order_qty", "numeric", "t0.OrderQty"),
                Map("pre_arrival", "numeric", "t0.PreArrival"),
                Map("logo", "boolean", "t0.Logo"),
                Map("dye_to_match", "boolean", "t0.DyeToMatch"),
                Map("fabric_types_id", "integer", "t0.FabricTypeId"),
                Map("group_fabric_type_id", "integer", "t0.GroupFabricTypeId"),
                Map("ld_code", "text", "t0.LDCode"),
                Map("ld_shadeband", "text", "t0.LDShadeband"),
                Map("swatch_approval", "text", "t0.SwatchApproval"),
                Map("ld_approval", "text", "t0.LDApproval"),
                Map("cs_ship_mode", "integer", "t0.CSShipMode"),
                Map("cs_price", "numeric", "t0.CSPrice"),
                Map("actual_ship_mode", "integer", "t0.ActualShipMode"),
                Map("unit_price", "numeric", "t0.UnitPrice"),
                Map("style_total_final_qty", "numeric", "t0.StyleTotalFinalQty"),
                Map("color_ext", "text", "t0.ColorExt"),
                Map("po_trim_rating_master_id", "integer", "t0.TrimTechnicalRatingId"),
                Map("fabric_color_ext", "text", "t0.FabricColorExt"),
                Map("trims_id", "integer", "t0.TrimId"),
                Map("swatch", "boolean", "t0.Swatch"),
                Map("labdip", "boolean", "t0.Labdip"),
                Map("costing_sheet_id", "integer", "t0.CostingSheetId"),
                Map("trim_costing_sheet_id", "integer", "t0.TrimCostingSheetId"),
                Map("expect_stock_in_date", "timestamp", "t0.ExpectStockinDate"),
                Map("ipo_trim_master_code", "text", "t0.IPOTrimMasterCode"),
                Map("style_trim_lab_dip_id", "integer", "t0.StyleTrimLabDipId"),
                Map("ref_style_fabric_lab_dip_id", "integer", "t0.Ref_StyleFabricLabDipId"),
                Map("created_by_user_id", "integer", "t0.CreatedByUserId"),
                Map("updated_by_user_id", "integer", "t0.UpdatedByUserId"),
                Map("updated_date", "timestamp", "t0.UpdatedDate"),
                Map("confirm_expect_stock_in_date", "timestamp", "t0.ConfirmExpectStockInDate"),
                Map("dimension_unit_id_of_technical", "integer", "t0.DimensionUnitIdOfTechnical"),
                Map("dimension_value_of_technical", "numeric", "t0.DimensionValueOfTechnical"),
                Map("ship_date", "timestamp", "t0.ShipDate"),
                Map("qty_after_rating", "numeric", "t0.QtyAfterRating"),
                Map("has_file_attachment", "boolean", "t0.Has_FileAttachment"),
                Map("drops_id", "integer", "t0.DropId"),
                Map("item_code", "text", "t0.ItemCode"),
                Map("process_type_id", "integer", "t0.ProcessTypeId"),
                Map("revised_stock_in_date", "timestamp", "t0.RevisedStockInDate"),
                Map("mer_cancel_remark", "text", "t0.MerCancelRemark"),
                Map("last_reason_revised_stock_in_date_id", "integer", "t0.LastReasonRevisedStockInDateId"),
                Map("shipment_date_max", "timestamp", "t0.ShipmentDateMax"),
                Map("shipment_internal_date_max", "timestamp", "t0.ShipmentInternalDateMax")
            ])
    ];
}
