using Application.Features.CentralDbSync.Config;
using Application.Features.CentralDbSync.Mapping;
using static Application.Features.CentralDbSync.Config.Rules.MappingRuleCatalogFactory;

namespace Application.Features.CentralDbSync.Config.Rules.IPO.Trim;

public sealed class IpoTrimMasterGroupMappingRuleCatalog : ITableMappingRuleCatalog
{
    public IReadOnlyList<TableMappingRule> GetRules() =>
    [
        Create(
            ruleName: "ERP.IPO.Trims.Masters.Groups",
            sourceTable: "ERP.IPO.Trims.Masters.Groups",
            sourcePrimaryKey: "IPOTrimMasterGroupId",
            targetTable: "ipo_trims_masters_groups",
            targetPrimaryKey: "ipo_trim_master_group_id",
            syncTier: "Hot",
            filterCompany: true,
            columns:
            [
                MapPk("ipo_trim_master_group_id", "integer", "t0.IPOTrimMasterGroupId"),
                Map("ipo_trim_master_group_code", "text", "t0.IPOTrimMasterGroupCode"),
                Map("ipo_trim_master_id", "integer", "t0.IPOTrimMasterId"),
                Map("company_id", "integer", "t0.CompanyId"),
                Map("ipo_trim_item_code_combined", "text", "t0.IPOTrimItemCodeCombined"),
                Map("pantone", "text", "t0.Pantone"),
                Map("ld_code", "text", "t0.LDCode"),
                Map("ld_shadeband", "text", "t0.LDShadeband"),
                Map("supplier_id", "integer", "t0.SupplierPartnerId"),
                Map("customer_id", "integer", "t0.CustomerPartnerId"),
                Map("trims_master_id", "integer", "t0.TrimSupplierId"),
                Map("size_id", "integer", "t0.SizeId"),
                Map("style_no_internals", "text", "t0.StyleNoInternals"),
                Map("style_internals", "text", "t0.StyleInternals"),
                Map("sku_no_internals", "text", "t0.SkuNoInternals"),
                Map("style_color_name_codes", "text", "t0.StyleColorNameCodes"),
                Map("dimension_of_technical", "text", "t0.DimensionOfTechnical"),
                Map("dimension_of_trim", "text", "t0.DimensionOfTrim"),
                Map("logo", "boolean", "t0.Logo"),
                Map("trim_supplier_code", "text", "t0.TrimSupplierCode"),
                Map("trim_supplier_name", "text", "t0.TrimSupplierName"),
                Map("units_id", "integer", "t0.UnitId"),
                Map("received", "boolean", "t0.Received"),
                Map("received_date", "timestamp", "t0.ReceivedDate"),
                Map("actual_received_date", "timestamp", "t0.ActualReceivedDate"),
                Map("received_user_id", "integer", "t0.ReceivedUserId"),
                Map("physical_inspection", "boolean", "t0.PhysicalInspection"),
                Map("physical_inspection_sample_size", "numeric", "t0.PhysicalInspectionSampleSize"),
                Map("meta_detection", "boolean", "t0.MetaDetection"),
                Map("meta_detection_sample_size", "numeric", "t0.MetaDetectionSampleSize"),
                Map("testing_for_stock_in", "boolean", "t0.TestingForStockin"),
                Map("testing_for_stock_in_sample_size", "numeric", "t0.TestingForStockinSampleSize"),
                Map("pur_remark", "text", "t0.PurRemark"),
                Map("commercial_remark", "text", "t0.CommercialRemark"),
                Map("mer_remark", "text", "t0.MerRemark"),
                Map("trim_inspection_matrix_id", "integer", "t0.TrimInspectionMatrixId"),
                Map("pre_arrival", "numeric", "t0.PreArrival"),
                Map("total_order_qty", "numeric", "t0.TotalOrderQty"),
                Map("inventory", "numeric", "t0.Inventory"),
                Map("actual_order_qty", "numeric", "t0.ActualOrderQty"),
                Map("raw_actual_order_qty", "numeric", "t0.RawActualOrderQty"),
                Map("buy_qty", "numeric", "t0.BuyQty"),
                Map("actual_unit_price", "numeric", "t0.ActualUnitPrice"),
                Map("actual_amount", "numeric", "t0.ActualAmount"),
                Map("raw_actual_amount", "numeric", "t0.RawActualAmount"),
                Map("surcharge", "numeric", "t0.Surcharge"),
                Map("avg_unit_price", "numeric", "t0.AVGUnitPrice"),
                Map("min_expect_stock_in_date", "timestamp", "t0.MinExpectStockInDate"),
                Map("min_ship_date", "timestamp", "t0.MinShipDate"),
                Map("test", "numeric", "t0.Test"),
                Map("return_request_id", "integer", "t0.ReturnRequestId"),
                Map("return_request_code", "text", "t0.ReturnRequestCode"),
                Map("confirm_expect_stock_in_date", "timestamp", "t0.ConfirmExpectStockInDate"),
                Map("eta_trim_received_date", "timestamp", "t0.ETATrimReceivedDate"),
                Map("work_type", "integer", "t0.WorkType"),
                Map("physical_aql_detail_id", "integer", "t0.Physical_AQLDetailId"),
                Map("physical_sample_size_detail_id", "integer", "t0.Physical_SampleSizeDetailId"),
                Map("physical_standard", "numeric", "t0.Physical_Standard"),
                Map("metal_aql_detail_id", "integer", "t0.Metal_AQLDetailId"),
                Map("metal_sample_size_detail_id", "integer", "t0.Metal_SampleSizeDetailId"),
                Map("metal_standard", "numeric", "t0.Metal_Standard"),
                Map("testing_aql_detail_id", "integer", "t0.Testing_AQLDetailId"),
                Map("testing_sample_size_detail_id", "integer", "t0.Testing_SampleSizeDetailId"),
                Map("testing_standard", "numeric", "t0.Testing_Standard"),
                Map("final_received_qty", "numeric", "t0.FinalReceivedQty"),
                Map("final_percent_received", "numeric", "t0.FinalPercentReceived"),
                Map("parent_id", "integer", "t0.ParentId"),
                Map("parent_root_id", "integer", "t0.ParentRootId"),
                Map("delivery_qty", "numeric", "t0.DeliveryQty"),
                Map("received_qty", "numeric", "t0.ReceivedQty"),
                Map("adjust_qty", "numeric", "t0.AdjustQty"),
                Map("actual_received_qty", "numeric", "t0.ActualReceivedQty"),
                Map("has_file_attachment", "boolean", "t0.Has_FileAttachment"),
                Map("item_code", "text", "t0.ItemCode"),
                Map("style_ids", "text", "t0.StyleIds"),
                Map("style_names", "text", "t0.StyleNames"),
                Map("season_codes", "text", "t0.SeasonCodes"),
                Map("season_ids", "text", "t0.SeasonIds"),
                Map("drop_ids", "text", "t0.DropIds"),
                Map("drop_codes", "text", "t0.DropCodes"),
                Map("process_type_names", "text", "t0.ProcessTypeNames"),
                Map("process_type_ids", "text", "t0.ProcessTypeIds"),
                Map("nominated_ids", "text", "t0.NominatedIds"),
                Map("nominated_names", "text", "t0.NominatedNames"),
                Map("po_status", "integer", "t0.POStatus"),
                Map("is_paid", "boolean", "t0.IsPaid"),
                Map("payment_updated_date", "timestamp", "t0.PaymentUpdatedDate"),
                Map("payment_updated_user_id", "integer", "t0.PaymentUpdatedUserId"),
                Map("max_rating", "numeric", "t0.MaxRating"),
                Map("avg_rating", "numeric", "t0.AvgRating"),
                Map("usd_unit_price", "numeric", "t0.USDUnitPrice"),
                Map("purch_actual_ship_mode", "integer", "t0.PurchActualShipMode"),
                Map("last_reason_revised_stock_in_date_id", "integer", "t0.LastReasonRevisedStockInDateId"),
                Map("revised_stock_in_date", "timestamp", "t0.RevisedStockInDate"),
                Map("color_exts", "text", "t0.ColorExts"),
                Map("insp_percentage_id", "integer", "t0.InspPercentageId"),
                Map("insp_percentage_detail_id", "integer", "t0.InspPercentageDetailId"),
                Map("physical_inspection_sample_size2", "integer", "t0.PhysicalInspectionSampleSize2"),
                Map("meta_detection_sample_size2", "integer", "t0.MetaDetectionSampleSize2"),
                Map("testing_for_stock_in_sample_size2", "integer", "t0.TestingForStockinSampleSize2"),
                Map("send_shipping_sample_to_pur_date", "timestamp", "t0.SendShippingSampleToPurDate"),
                Map("pur_received_shipping_sample_date", "timestamp", "t0.PurReceivedShippingSampleDate"),
                Map("fabric_color_exts", "text", "t0.FabricColorExts"),
                Map("po_type", "integer", "t0.POType"),
                Map("stock_in_quantity", "numeric", "t0.StockinQuantity"),
                Map("stockout_quantity", "numeric", "t0.StockoutQuantity"),
                Map("stock_adjust", "numeric", "t0.StockAdjust"),
                Map("shipment_date_max", "timestamp", "t0.ShipmentDateMax"),
                Map("shipment_internal_date_max", "timestamp", "t0.ShipmentInternalDateMax"),
                Map("stock_balance", "numeric", "t0.StockBalance"),
                Map("first_stock_in_date", "timestamp", "t0.FirstStockInDate"),
                Map("last_stock_in_date", "timestamp", "t0.LastStockinDate"),
                Map("last_physical_inspection_checked_date", "timestamp", "t0.LastPhysicalInspection_CheckedDate"),
                Map("last_meta_detection_checked_date", "timestamp", "t0.LastMetaDetection_CheckedDate"),
                Map("last_testing_for_stock_in_checked_date", "timestamp", "t0.LastTestingForStockin_CheckedDate"),
                Map("combined_purchase_order_ids", "text", "t0.CombinedPurchaseOrderIds")
            ])
    ];
}
